### ISSUE TITLE
Pdf Form data not retrived and not showing any validation or error.

### ISSUE THREAD

**Issue by testdefsoft** [mikehaertl/phpwkhtmltopdf#214]
Hi, 
I'm working with the PHP 7 and not able retrive data from pdf form fields.
I'm using follwoing php code index.php-
<pre>

require('vendor\autoload.php');
use mikehaertl\pdftk\Pdf;

$pdf = new Pdf('template.pdf');
$data = $pdf->getData();
print_r($data);

</pre>

This(index.php) file is located in the outside of vendor directory and template.pdf file is also located in same directory.
Please have a look on the issue and check what is the issue we are facing.

**Comment by mikehaertl** [comment]
What is the output of your script? And which version of pdftk are you using?

**Comment by mikehaertl** [comment]
Wait a minute - guess you're in the wrong project here. This is phpwkhtmltopdf - for creating PDF. Your issue is with pdftk, so you should open the issue there.

Before you do so, please also first try, if it works on the command line: `pdftk dump_data_utf8 template.pdf`. If it doesn't work there it's not a problem of php-pdftk.
