### ISSUE TITLE
The text is not added when I convert it to pdf

### ISSUE THREAD

**Issue by richardsonoge** [mikehaertl/phpwkhtmltopdf#400]
I converted a secure PDF file without a password to HTML. Now I'm using this library to convert my HTML file to PDF but unfortunately the text isn't added and I don't know why.
**Here is my code:**
```
<?php
require 'vendor/autoload.php';
use mikehaertl\wkhtmlto\Pdf;

// You can pass a filename, a HTML string, an URL or an options array to the constructor
$pdf = new Pdf('/opt/lampp/htdocs/ar-11.html');
$pdf->saveAs('/opt/lampp/htdocs/ar.pdf');
```

**Here is the original PDF:**
![Screenshot from 2023-09-27 18-32-11](https://github.com/mikehaertl/phpwkhtmltopdf/assets/37945903/1f5884b9-5eca-4384-a163-5093536dcdbc)

**Here is the PDF converted from HTML to PDF:**
![Screenshot from 2023-09-27 18-32-20](https://github.com/mikehaertl/phpwkhtmltopdf/assets/37945903/58c8fa04-2352-464b-8fb5-e1233cbaaa42)

**Can you help me to add the text in the conversion from HTML to PDF?**

**Comment by mikehaertl** [comment]
I can not provide any help on this kind of issues. Your problem is also not related to our library but rather wkthmltopdf itself. 

Getting wkhtmltopdf to work with special styles can be tricky especially when it comes to fonts. In your case it's probably easier if you use wkhtmltopdf from the command line first: Prepare the HTML and related CSS files and make sure that the font paths in the CSS file point to files exist and are readable.

**Comment by richardsonoge** [comment]
Hello!
Thank you for replying. I would like to ask you how can I make sure that the font paths in the CSS file point to the files since the html file is working correctly?

**Comment by richardsonoge** [comment]
> I can not provide any help on this kind of issues. Your problem is also not related to our library but rather wkthmltopdf itself.
> 
> Getting wkhtmltopdf to work with special styles can be tricky especially when it comes to fonts. In your case it's probably easier if you use wkhtmltopdf from the command line first: Prepare the HTML and related CSS files and make sure that the font paths in the CSS file point to files exist and are readable.

Hello!
Thank you for replying. I would like to ask you how can I make sure that the font paths in the CSS file point to the files since the html file is working correctly?

**Comment by mikehaertl** [comment]
Please understand that I can not provide more help as this is a bug reporting system and not a support forum. Again: Try with wkhtmltopdf without our library first. Play around with file paths (full path instead of relative path) inside the CSS. Also try to learn more about the CSS options regarding fonts.

**Comment by richardsonoge** [comment]
> Please understand that I can not provide more help as this is a bug reporting system and not a support forum. Again: Try with wkhtmltopdf without our library first. Play around with file paths (full path instead of relative path) inside the CSS. Also try to learn more about the CSS options regarding fonts.

I understand. You know I got this file from pdf2htmlex and font files or fonts has no link in my server. I don't know what to do. I'll try in the CSS code to see what happens.
