### ISSUE TITLE
header-html and footer-html not showing

### ISSUE THREAD

**Issue by NadavSi** [mikehaertl/phpwkhtmltopdf#402]
hello, i've been trying the header and footer options when converting html to pdf but i cant make this work. 
this is a function i wrote trying to create a pdf and the imports from the package:

use mikehaertl\wkhtmlto\Pdf;
use mikehaertl\tmp\File;

class PDFBuilder {
    public function generatePdf()
    {
        $pdf = new Pdf;
        $this->generalOptions['header-html'] = "<div>this is the footer of the pdf</div>";
        // $this->generalOptions['header-html'] = $this->headerContent; //also tried like this
        $this->generalOptions['footer-html'] = new File($this->footerContent, '.html');
        $pdf->setOptions($this->generalOptions);
        $content = $this->bodyContent; //just some html from another file
        $pdf->addPage($content, $this->pageOptions);
        return $pdf->toString();
    }
}

these are the options i inject from outside to the class in generalOptions:
$options = [
            'no-outline',
            'encoding' => 'UTF-8',
            'margin-top'    => 0,
            'margin-right'  => 0,
            'margin-bottom' => 0,
            'margin-left'   => 0,
            'disable-smart-shrinking',
        ];
and i add the header and footer in the function
what i get is this: 
![image](https://github.com/mikehaertl/phpwkhtmltopdf/assets/19567670/e455e707-fa57-464d-936f-caa622e4b8b0)

please help me figure out what is wrong

**Comment by mikehaertl** [comment]
If you pass the content as a string it must be valid HTML (i.e. it must start with `<html>`, see the regex [here](https://github.com/mikehaertl/phpwkhtmltopdf/blob/master/src/Pdf.php#L21)), otherwhise our library can't detect it. 

I'd recommend not to use `new File()` directly as this is rather an internal class.

Apart from that I can not really help you much as your problem is more about how to use `wkhtmltopdf` and not our library. I would start with `wkhtmltopdf` on the command line first and try to start with very simple options (e.g. no styling, etc...) just to figure out how the header/footer options of wkhtmltopdf work.

I could imagine that margin=0 is also a problem as you leave no room for the headers - but not sure about it.
